version: '3'
services:
  controller:
    build:
      context: ./controller
    ports:
      - 4200:4200
    container_name: prefect_controller
    networks:
      - prefect_network
    depends_on:
      - postgres

  worker:
    build:
      context: ./worker
    container_name: prefect_worker
    networks:
      - prefect_network
    depends_on:
      - controller
    environment:
      - POOL_NAME=${POOL_NAME}
      - PREFECT_API_URL=http://prefect_controller:4200/api
    restart: "on-failure"

  postgres:
    image: postgres:15
    container_name: postgres
    networks:
      - prefect_network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  prefect_network: